import {ils,papi,ROUTE} from './navigation.js';
export class UI{
 constructor(){this.$=id=>document.getElementById(id);this.pfd=this.$('pfd');this.ctx=this.pfd.getContext('2d');this.toastT=0;this.lastMission=1;}
 showHud(){this.$('boot').classList.add('hidden');this.$('hud').classList.remove('hidden');}
 toast(t){const e=this.$('toast');e.textContent=t;e.classList.add('show');clearTimeout(this.toastT);this.toastT=setTimeout(()=>e.classList.remove('show'),1600);}
 update(s,input,weather,traffic,worldStatus,missionIndex){const set=(id,v)=>{const e=this.$(id);if(e)e.textContent=v;};set('h-alt',Math.round(s.alt*3.28084).toString().padStart(5,'0'));set('h-ias',Math.round(s.ias*1.94384).toString().padStart(3,'0'));set('h-tas',Math.round(s.tas*1.94384).toString().padStart(3,'0'));set('h-hdg',Math.round((s.heading+360)%360).toString().padStart(3,'0'));set('h-vs',Math.round(s.vs*196.85));set('h-aoa',(s.alpha/Math.PI*180).toFixed(1));set('h-beta',(s.beta/Math.PI*180).toFixed(1));set('h-g',s.g.toFixed(2));set('h-mach',s.mach.toFixed(2));set('h-thr',Math.round(s.throttle*100));set('h-n1',s.N1.toFixed(0));set('h-phase',s.phase);set('h-src',input.source);set('h-wx',weather.source);set('h-wind',weather.wind.speedKt?`${Math.round(weather.wind.speedKt)} KT / ${weather.wind.dirDeg??'VRB'}`:'CALM');set('h-fuel',Math.round(s.fuel));set('h-score',String(s.score));set('h-world',worldStatus);set('h-traffic',traffic?.status?.()||'OFF');set('h-battery',s.battery?'ON':'OFF');set('h-eng',s.engineRunning?'RUN':s.starter?'START':'OFF');set('h-flaps',String(s.flaps));set('h-gear',s.gear?'DOWN':'UP');
  const i=ils(s),active=i.distance<18000;this.$('approach').classList.toggle('hidden',!active);if(active){this.$('approach').dataset.nav='ICMB 109.1 / 3.0°';set('a-loc',(i.locDeg>=0?'R ':'L ')+Math.abs(i.locDeg).toFixed(1)+'°');set('a-gs',(i.gsErr>=0?'+':'')+Math.round(i.gsErr)+' m');set('a-dh',Math.round(i.dhFt));set('a-thr',i.dmeNm.toFixed(1)+' NM');const p=papi(s);this.$('papi').innerHTML=p.map(x=>`<i class="papi ${x.toLowerCase()}"></i>`).join('');}
  const target=ROUTE[Math.min(missionIndex,ROUTE.length-1)];set('mis-title','MISSION // '+(target?.mission||'CJB'));set('mis-sub',target?`${Math.round(i.dmeNm*10)/10} NM · ${target.name}`:'MISSION COMPLETE');set('replay',input.events?.rec?'● REC':'○ REC');
 }
 renderPFD(s){const w=this.pfd.clientWidth||420,h=this.pfd.clientHeight||270,dpr=Math.min(devicePixelRatio||1,2);if(this.pfd.width!==w*dpr||this.pfd.height!==h*dpr){this.pfd.width=w*dpr;this.pfd.height=h*dpr;}const c=this.ctx;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const cx=w/2,cy=h*.56,scale=h/85,roll=s.phi,pitch=s.theta;c.save();c.translate(cx,cy);c.rotate(-roll);const hy=pitch*scale;c.fillStyle='#2d6189';c.fillRect(-w*1.3,-h*1.2+hy,w*2.6,h*1.2);c.fillStyle='#4a392c';c.fillRect(-w*1.3,hy,w*2.6,h*1.2);c.strokeStyle='#fff';c.lineWidth=1.5;c.beginPath();c.moveTo(-w,hy);c.lineTo(w,hy);c.stroke();for(let deg=-30;deg<=30;deg+=10){if(!deg)continue;const y=hy-deg*scale;c.strokeStyle='#ffffff99';c.beginPath();c.moveTo(-20,y);c.lineTo(-6,y);c.moveTo(6,y);c.lineTo(20,y);c.stroke();c.fillStyle='#fff9';c.font='9px monospace';c.fillText(String(Math.abs(deg)), -36,y+3);c.fillText(String(Math.abs(deg)), 25,y+3);}c.restore();c.strokeStyle='#ffd35c';c.lineWidth=2;c.beginPath();c.moveTo(cx-55,cy);c.lineTo(cx-15,cy);c.moveTo(cx+15,cy);c.lineTo(cx+55,cy);c.stroke();c.fillStyle='#62c9ff';c.font='bold 14px monospace';c.fillText(`${Math.round(s.ias*1.94384)} KT`,14,24);c.fillText(`${Math.round(s.alt*3.28084)} FT`,w-110,24);c.fillText(`${Math.round(s.heading).toString().padStart(3,'0')}°`,cx-18,24);c.fillStyle='#61ffae';c.fillText(`${Math.round(s.vs*196.85)} FPM`,14,h-18);c.fillStyle=s.engineRunning?'#61ffae':'#ff5b6d';c.fillText(`ENG ${s.engineRunning?'RUN':'OFF'}`,w-82,h-18);}
}
