export class World{
 constructor(cfg,onStatus=()=>{}){this.cfg=cfg;this.onStatus=onStatus;this.viewer=null;this.aircraftEntity=null;this.photoreal=false;this.buildingEntities=[];this.routeEntities=[];this.lastCameraAt=0;this.lastSampleAt=0;this.groundSampleBusy=false;}
 async init(){this.onStatus('INITIALIZING GLOBE');try{Cesium.Ion.defaultAccessToken=this.cfg.cesiumIonToken||undefined;this.viewer=new Cesium.Viewer('globe',{animation:false,timeline:false,geocoder:false,homeButton:false,sceneModePicker:false,baseLayerPicker:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,baseLayer:new Cesium.ImageryLayer(new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',credit:'© OpenStreetMap contributors'})),terrainProvider:new Cesium.EllipsoidTerrainProvider(),shouldAnimate:true,requestRenderMode:false,msaaSamples:2});this.viewer.scene.skyAtmosphere.show=true;this.viewer.scene.globe.depthTestAgainstTerrain=true;this.viewer.scene.fog.enabled=true;this.viewer.scene.fog.density=.00002;const ok=await this.tryPhotoreal();if(!ok){await this.tryIonTerrain();await this.loadBuildingsFallback();this.onStatus('OPEN FALLBACK');}else this.onStatus('GOOGLE PHOTOREAL 3D');return true;}catch(e){console.error(e);this.onStatus('WORLD DEGRADED');return false;}}
 async tryPhotoreal(){try{let tileset=null;if(this.cfg.googleMapsApiKey&&typeof Cesium.createGooglePhotorealistic3DTileset==='function'){tileset=await Cesium.createGooglePhotorealistic3DTileset({key:this.cfg.googleMapsApiKey,onlyUsingWithGoogleGeocoder:true});}else if(this.cfg.cesiumIonToken){const res=await Cesium.IonResource.fromAssetId(2275207,{accessToken:this.cfg.cesiumIonToken});tileset=await Cesium.Cesium3DTileset.fromUrl(res,{maximumScreenSpaceError:12,cacheBytes:1536*1024*1024,maximumCacheOverflowBytes:1024*1024*1024});}if(!tileset)return false;tileset.maximumScreenSpaceError=10;this.viewer.scene.primitives.add(tileset);this.viewer.scene.globe.show=false;this.photoreal=true;return true;}catch(e){console.warn('Photorealistic 3D unavailable:',e);return false;}}
 async tryIonTerrain(){try{if(!this.cfg.cesiumIonToken)return false;const terrain=await Cesium.CesiumTerrainProvider.fromIonAssetId(1,{requestVertexNormals:true,requestWaterMask:true});this.viewer.terrainProvider=terrain;this.viewer.scene.globe.show=true;return true;}catch(e){console.warn('Ion terrain unavailable:',e);return false;}}
 async loadBuildingsFallback(){try{const url='/api/buildings?bbox=11.005,76.985,11.055,77.060';const d=await fetch(url,{cache:'no-store'}).then(r=>r.json());let count=0;for(const el of(d.elements||[])){if(count>=900)break;const geom=el.geometry||[];const pts=geom.map(p=>Cesium.Cartesian3.fromDegrees(p.lon,p.lat));if(pts.length<4)continue;const levels=Number(el.tags?.['building:levels']);const height=Number(el.tags?.height)|| (Number.isFinite(levels)?levels*3.2:9);this.buildingEntities.push(this.viewer.entities.add({polygon:{hierarchy:pts,height:0,extrudedHeight:Math.max(3,height),material:Cesium.Color.fromBytes(90,112,130,190),outline:true,outlineColor:Cesium.Color.fromBytes(20,30,42,220)}}));count++;}this.onStatus(`OSM 3D BUILDINGS · ${count}`);}catch(e){console.warn('Building fallback unavailable:',e);}}
 spawnAircraft(state){if(!this.viewer)return;const pos=Cesium.Cartesian3.fromDegrees(state.lng,state.lat,state.alt);this.aircraftEntity=this.viewer.entities.add({position:pos,orientation:Cesium.Transforms.headingPitchRollQuaternion(pos,new Cesium.HeadingPitchRoll(state.psi,state.theta,-state.phi)),model:{uri:'/aircraft.glb',scale:1.7,minimumPixelSize:54,maximumScale:140}});}
 updateAircraft(state){if(!this.aircraftEntity)return;const pos=Cesium.Cartesian3.fromDegrees(state.lng,state.lat,state.alt);this.aircraftEntity.position=pos;this.aircraftEntity.orientation=Cesium.Transforms.headingPitchRollQuaternion(pos,new Cesium.HeadingPitchRoll(state.psi,state.theta,-state.phi));}
 drawRoute(route){if(!this.viewer)return;for(const e of this.routeEntities)this.viewer.entities.remove(e);this.routeEntities=[];for(const p of route){this.routeEntities.push(this.viewer.entities.add({position:Cesium.Cartesian3.fromDegrees(p.lng,p.lat,p.alt||40),point:{pixelSize:8,color:Cesium.Color.YELLOW,outlineColor:Cesium.Color.BLACK,outlineWidth:2},label:{text:p.name,font:'10px monospace',fillColor:Cesium.Color.WHITE,showBackground:true,backgroundColor:Cesium.Color.BLACK.withAlpha(.55),pixelOffset:new Cesium.Cartesian2(8,-8)}}));}}
 updateGround(state,now){if(!this.viewer||this.groundSampleBusy||now-this.lastSampleAt<1000)return;this.lastSampleAt=now;const globe=this.viewer.scene.globe;if(!globe?.getHeight)return;this.groundSampleBusy=true;try{const cart=Cesium.Cartographic.fromDegrees(state.lng,state.lat);const h=globe.getHeight(cart);if(Number.isFinite(h))state.groundAlt=h;}finally{this.groundSampleBusy=false;}}
 frame(state,mode,now){if(!this.viewer)return;this.updateAircraft(state);if(now-this.lastCameraAt<33)return;this.lastCameraAt=now;if(mode==='free')return;const center=Cesium.Cartesian3.fromDegrees(state.lng,state.lat,state.alt);if(mode==='cockpit'){this.viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(state.lng,state.lat,state.alt+1.15),orientation:{heading:state.psi,pitch:state.theta,roll:-state.phi}});}else{const enu=Cesium.Transforms.eastNorthUpToFixedFrame(center);const h=state.psi;let back=45,up=15,fwd=35;if(mode==='chase'){back=95;up=28;fwd=30;}if(mode==='follow'){back=65;up=20;fwd=42;}const off=Cesium.Matrix4.multiplyByPoint(enu,new Cesium.Cartesian3(-Math.sin(h)*back,-Math.cos(h)*back,up),new Cesium.Cartesian3());const target=Cesium.Matrix4.multiplyByPoint(enu,new Cesium.Cartesian3(Math.sin(h)*fwd,Math.cos(h)*fwd,3),new Cesium.Cartesian3());this.viewer.camera.lookAt(off,Cesium.Cartesian3.subtract(target,off,new Cesium.Cartesian3()));}}
}
